<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    fill="none"
    viewBox="0 0 106 106"
  >
    <circle
      cx="53"
      cy="53"
      r="53"
      fill="url(#avatar-pattern)"
    />
    <defs>
      <pattern
        id="avatar-pattern"
        width="1"
        height="1"
        patternContentUnits="objectBoundingBox"
      >
        <use
          xlink:href="#avatar-img"
          transform="scale(.00943)"
        />
      </pattern>
      <image
        id="avatar-img"
        width="106"
        height="106"
        preserveAspectRatio="none"
      />
    </defs>
  </svg>
</template>
