ALTER TABLE "reviewOnService" ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'APPROVED';
ALTER TABLE "reviewOnService" ADD COLUMN IF NOT EXISTS author_member_id BIGINT REFERENCES members(id) ON DELETE SET NULL;
