server {
  listen 80;
  server_name localhost;

  resolver 127.0.0.11 valid=10s ipv6=off;

  location /api/ {
    set $backend http://backend:3000;
    proxy_pass $backend$request_uri;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    client_max_body_size 10m;
  }
  location / {
    root /static/landing-frontend;
    try_files $uri $uri/ /index.html;
    index index.html;
    location ~* \.html$ {
      add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
  }

  location /admin {
    alias /static/admin-frontend;
    try_files $uri $uri/ /admin/index.html;
    index index.html;
    location ~* /admin/.*\.html$ {
      add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
  }

  location /platform {
    alias /static/platform-frontend;
    try_files $uri $uri/ /platform/index.html;
    index index.html;
    location ~* /platform/.*\.html$ {
      add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
  }
}
