export const reasonLabels: Record<string, string> = {
  event_attend: 'Посещение событий',
  event_host: 'Проведение событий',
  review_community: 'Отзывы (сообщество)',
  review_service: 'Отзывы (услуги)',
  resume_upload: 'Загрузка резюме',
  referal_create: 'Создание рефералов',
  referal_conversion: 'Конверсия рефералов',
  profile_complete: 'Заполнение профиля',
  weekly_activity: 'Еженедельная активность',
  monthly_active: 'Ежемесячная активность',
  streak_4weeks: 'Серия 4 недели',
  admin_manual: 'Начисление вручную',
  task_create: 'Создание заданий',
  task_execute: 'Выполнение заданий',
  marketplace_create: 'Публикация объявлений',
  marketplace_buy: 'Покупки',
  chat_quest: 'Квесты в чатах',
  chatter_of_week: 'Чаттер недели',
  kudos_received: 'Благодарности',
  raffle_spend: 'Розыгрыши',
  casino_bet: 'Ставки мини-игр',
  casino_win: 'Выигрыши мини-игр',
}
