name: Update platform Frontend Submodule

on:
  repository_dispatch:
    types: [platform-frontend-update]
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      
      - name: Update submodule
        run: |
          cd platform-frontend
          git fetch
          git pull
          cd ..
          git add platform-frontend
      
      - name: Commit and push if there are changes
        run: |
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update platform-frontend submodule to latest commit"
            git push
          fi 